language: node_js

node_js:
    - 8

# Trigger a push build on master + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
    only:
        - master

cache:
    directories:
        - ~/.npm

# Retry install on fail to avoid failing a build on network/disk/external errors
install:
    - travis_retry npm install

script:
    - npm run test
    - npm run build

after_success:
    - npm run semantic-release
